cors: # Define quais endpoints podem acessar os métodos da API
  originPatterns: http://localhost:3000,http://localhost:8080,
security:
  jwt:
    token:
      secret-key: 97cwsc97
      expire-length: 3600000 # Define o tempo de duração do token para uma hora
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/java_spring_restfull_api_database?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show_sql: false
    open-in-view: false